### Variables
@apiURL = http://localhost:3001/api

###
GET {{apiURL}}/notes HTTP/1.1

###
DELETE  {{apiURL}}/notes/1 HTTP/1.1

###
POST {{apiURL}}/notes HTTP/1.1
content-type: application/json

{
    "content": "sample",
		"important": true
}
